#公用配置
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#Spring 配置
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #配置文件上传
  servlet:
    multipart:
      #默认 为true允许附件上传
      enabled: true
      #临时文件存储位置
      #location: opt/tmp/file
      #设定一定大小文件就先写到临时文件中 0为不设定阈值
      file-size-threshold: 0
      #单个文件最大长度
      max-file-size: 5MB
      #单次Request 請求允许的最大文件长度
      max-request-size:  10MB
  #视图配置
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl

  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    password:
    username:

  #Redis 配置
  redis:
    sentinel:
      master:
      nodes:
    database: 7
    jedis:
      pool:
        #最小空闲数
        min-idle: 10
        #最大空闲数
        max-idle: 200
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
        max-active: 600
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 3000s

  ##Elastic的服务器节点'
  data:
    elasticsearch:
      cluster-nodes:

  ##Session 存储位置设置
  session:
    store-type: redis
    redis:
      ## 保存会话立即保存到redis
      flush-mode: immediate
  #热部署 重启 #热部署扫包位置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.dawei.boot.boothelloword.entity

#日志
logging:
  config: classpath:logconfig/logback.xml
  path: /home/log/boot-hello-world



---
#开发环境配置
server:
  #端口
  port: 80
spring:
  profiles: dev
  #redis配置
  #Redis 配置
  redis:
    sentinel:
      master:
      nodes:
    database: 7
    jedis:
      pool:
        #最小空闲数
        min-idle: 10
        #最大空闲数
        max-idle: 200
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
        max-active: 600
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 3000s


  ##数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    password:
    username:
    dbcp2:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100


####项目服务配置
zookeeper.address.url=

