
#开发环境配置
server:
  #端口
  port: 80
spring:
#  #redis配置
#  #Redis 配置
#  redis:
#    sentinel:
#      master:
#      nodes:
#    database: 7
#    jedis:
#      pool:
#        #最小空闲数
#        min-idle: 10
#        #最大空闲数
#        max-idle: 200
#        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
#        max-active: 600
#        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        max-wait: 3000s


  ##数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/myDataBase
    password:
    username: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true