#公用配置
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#Spring 配置
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #配置文件上传
  servlet:
    multipart:
      #默认 为true允许附件上传
      enabled: true
      #临时文件存储位置
      #location: opt/tmp/file
      #设定一定大小文件就先写到临时文件中 0为不设定阈值
      file-size-threshold: 0
      #单个文件最大长度
      max-file-size: 5MB
      #单次Request 請求允许的最大文件长度
      max-request-size:  10MB
  #视图配置
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl

  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.201.88:3306/testDataBase?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    password: 93d837851db73e6650acfc9a1d63b64d
    username: dawei21

  #Redis 配置
  redis:
    sentinel:
      master: my26601master
      nodes: jzupsentinel01.redist.djdns.cn:26601,jzupsentinel01.redist.djdns.cn:26602,jzupsentinel01.redist.djdns.cn:26603
    database: 7

  #热部署 重启 #热部署扫包位置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java



#日志
logging:
  config: classpath:logconfig/logback.xml
  path: /home/log/boot-hello-world



---
#开发环境配置
server:
  #端口
  port: 80
spring:
  profiles: dev
#  #redis配置
#  redis:
#    database: 2
#    host: 10.37.18.94
#    port: 18300
#    password:      # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    pool:
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
#  datasource:
#    url: jdbc:mysql://10.37.18.109:3606/dbdj_house_jzupadmin?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
#    username: daojia_root
#    password: aaa111
