#公用配置
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8


#Spring 配置
spring:
  #视图配置
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl

   #热部署 重启 #热部署扫包位置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
